services:
  zookeeper:
      mem_limit: 500000000
      image: 'bitnami/zookeeper:latest'
      networks:
          - ergo-net
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
      mem_limit: 1000000000
      depends_on:
        - zookeeper
      image: 'bitnami/kafka:latest'
      networks:
        - ergo-net
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
  redis:
      mem_limit: 50000000
      container_name: redis
      image: 'redis:latest'
      networks:
          - ergo-net
      volumes:
          - redis-data:/data
  utxotracker:
    mem_limit: 500000000
    container_name: utxotracker
    depends_on:
      - redis
      - kafka
    build: 
      context: .
      dockerfile: ./modules/utxo-tracker/src/main/resources/Dockerfile
    networks:
      - ergo-net
  poolresolver:
    mem_limit: 500000000
    container_name: poolresolver
    build: 
      context: .
      dockerfile: ./modules/pool-resolver/src/main/resources/Dockerfile
    depends_on:
      - kafka
    networks:
      - ergo-net
    env_file: config.env
    volumes:
      - rocks-data:/var/tmp
  ammexecutor:
    mem_limit: 500000000
    container_name: ammexecutor
    build: 
      context: .
      dockerfile: ./modules/amm-executor/src/main/resources/Dockerfile
    depends_on:
      - kafka
    networks:
      - ergo-net
    env_file: config.env
networks:
  ergo-net:
volumes:
    redis-data:
    rocks-data: